# Generated by Django 4.2.7 on 2023-11-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shopping_cart_recipe_ingredient_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Название ингредиента', max_length=200, verbose_name='Название'),
        ),
    ]
