# Generated by Django 4.2.7 on 2023-11-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1, help_text='Колличество ингредиента', verbose_name='Колличество'),
            preserve_default=False,
        ),
    ]
