# Generated by Django 4.2.7 on 2023-11-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
