# Generated by Django 4.2.7 on 2023-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_options_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Заблокирован ли пользователь', verbose_name='Блокировка'),
        ),
    ]
